### ISSUE TITLE
Merge two sorted arrays without Extra Space

### ISSUE THREAD

**Issue by Amisha2093** [anuragverma108/DSA-Placement-Probems#31]
Problem Statement:

Given two sorted arrays arr1[] and arr2[] of sizes n and m in non-decreasing order. Merge them in sorted order without using any extra space. Modify arr1 so that it contains the first N elements and modify arr2 so that it contains the last M elements.

Input: 
n = 4, arr1[] = [1 3 5 7] 
m = 5, arr2[] = [0 2 6 8 9]
Output: 
arr1[] = [0 1 2 3]
arr2[] = [5 6 7 8 9]
Explanation:
After merging the two non-decreasing arrays, we get, 
0 1 2 3 5 6 7 8 9.

**Comment by Amisha2093** [comment]
Hi @anuragverma108, I want to work on this problem. Can you please assign this to me.

**Comment by anuragverma108** [comment]
Assigned! @Amisha2093

**Comment by Amisha2093** [comment]
Hi @anuragverma108,

Please merge the PR #32, thanks.

**Comment by anuragverma108** [comment]
Merged!

**Comment by Amisha2093** [comment]
Hi @anuragverma108,

I am getting this contribution as "NOT-PARTICIPATING". Please help me to get my contribution counted.
