### ISSUE TITLE
Code :  Max data node

### ISSUE THREAD

**Issue by Anujjoshi021** [anuragverma108/DSA-Placement-Probems#49]
Problem Statement:  
Given a generic tree, find and return the node with maximum data. You need to return the node which is having maximum data.
Return null if tree is empty.

Input format :
The first line of input contains data of the nodes of the tree in level order form. The order is: data for root node, number of children to root node, data of each of child nodes and so on and so forth for each node. The data of the nodes of the tree is separated by space.

Output Format :
The first and only line of output contains the data of the node with largest data in the given tree.

please assign this issue to me and add a Hacktoberfest label to it.

**Comment by anuragverma108** [comment]
Assigned !
