### ISSUE TITLE
Kadane Algorithm for finding maximum subarray sum.

### ISSUE THREAD

**Issue by ashish5433** [anuragverma108/DSA-Placement-Probems#8]

**Comment by anuragverma108** [comment]
Assigned!

**Comment by AKG1301** [comment]
@anuragverma108 
I already made pr for this issue
https://github.com/anuragverma108/DSA-Placement-Probems/pull/10
can you please merge this pr.

**Comment by AKG1301** [comment]
@anuragverma108 
why this issue is the non-participating issue in hacktoberfest?

**Comment by anuragverma108** [comment]
@AKG1301 Labelled with hacktoberfest tag. Check now!!

**Comment by AKG1301** [comment]
@anuragverma108 
![image](https://github.com/anuragverma108/DSA-Placement-Probems/assets/52539720/669d3368-c44d-4ff9-adae-5b8ccdc9fa9e)

**Comment by anuragverma108** [comment]
Refresh & see it after few minutes

**Comment by AKG1301** [comment]
@anuragverma108 
it is working 
thanks
