### ISSUE TITLE
Trapping Rain Water

### ISSUE THREAD

**Issue by Amisha328** [anuragverma108/DSA-Placement-Probems#9]
Given n non-negative integers representing an elevation map where the width of each bar is 1, compute how much water it is able to trap after rain.

![image](https://github.com/anuragverma108/DSA-Placement-Probems/assets/58816552/153b31d9-c2a6-4a3c-aee4-4c1dc10de38c)

**Comment by Amisha328** [comment]
Hi @anuragverma108, please assign the issue to me. Thanks !!

**Comment by anuragverma108** [comment]
Assigned!

**Comment by Amisha328** [comment]
Hi @anuragverma108,

Please review and accept the PR #15. Thank you !! :)

**Comment by Amisha328** [comment]
Hi @anuragverma108, 

Is this repository not part of hacktoberfest23?

![image](https://github.com/anuragverma108/DSA-Placement-Probems/assets/58816552/f3c0b146-da70-4611-b004-004ff1dca855)

**Comment by anuragverma108** [comment]
> Hi @anuragverma108,
> 
> Is this repository not part of hacktoberfest23?
> 
> ![image](https://user-images.githubusercontent.com/58816552/274594789-f3c0b146-da70-4611-b004-004ff1dca855.png)

It is part of Hactoberfest. I've labelled your PR as hacktoberfest-accepted. Refresh the Hacktoberfest page and see again

**Comment by Amisha328** [comment]
Yeah, I can see now. Thanks :)
